server:
  port: 8080
  servlet:
    session:
      timeout: 300m
spring:

  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
  datasource:
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_dorm?useUnicode=true&characterEncoding=UTF8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# Swagger UI
knife4j:
  enable: true
  basic:
    enable: true
    username: root
    password: 123456
