server:
  port: 8080
spring:
  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
  datasource:
    username: root
    password: zxc200219
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_dorm?useUnicode=true&characterEncoding=UTF8